# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'initial/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '*'
    azureSubscription: 'Visual Studio Enterprise(1d99e725-53aa-438b-96af-f6812140ffd8)'
    Destination: 'AzureVMs'
    storage: 'stg3hrd4btwztphe'
    resourceGroup: 'JAVADEMOUSINGAZ_GROUP'
    MachineNames: 'demoVMJava'
    vmsAdminUserName: 'jganapin'
    vmsAdminPassword: 'AttackOnTitan20!'
    TargetPath: '/home/jganapin/build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true