# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'initial/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: '-----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn NhAAAAAwEAAQAAAgEAyXFtXBUd+G2VvS9RvKyKyddKD2tpTbyefrXPr/0Ac3W3S7N+O7RD i+PmEYDZPXKMC7LMqmT3ZC4S52NM5ZAHhnCv2WzhtokpCE8x78szkarEu5T1KbejDcXXSl W3a1WrSIkru3oNSREFDJTjyUb3v4oZ++wZdXuxPIl1zrRT/lDQahJsyL96QKGX7zZC3Koi q8WLSAiZusgOUSxgCE3EfA/EK+UTvPeYlDZBIQ/2dIUeuLhYlntQxRvkEXGIoF5t3nk+dn CfccJJ2tcsjB0GERPNiOHvNs1pmJku8BZORaVxPYHfiZxvzHOx/pvVJTO/ZsGCr8LJGGdB Vtyl6lF8IrFHMzlwTq0pmcPU/OsHWmtBbswX9SYLA80dSCKeFgNvpKBZwffPMVTknny6VW 3oEv+4Hr9LiDBdU0enW+QABuBw60PSgZQcSllXk8WdV2hlkeCBDL4/X36WIj/8m14et0Bs e7IbpzJAe+INqg0TE5gqXeTmvJVXKsI0GUYWclx+mAfmgMxS+prS3FaN5Abwc07lFcNhEv tzFuhQrHS4u7lME7SrxcH6plLeRPb7AAB6gnBRCTUmCzQCSc304QSHYEX74KL1qabyzaKY laD30ptc4MV++UoklGRWR9mzkCIGgqpF5EDW9yT+SWBAMqwAPi7xWmA5UoS738alF/6AIJ kAAAdISJdDqkiXQ6oAAAAHc3NoLXJzYQAAAgEAyXFtXBUd+G2VvS9RvKyKyddKD2tpTbye frXPr/0Ac3W3S7N+O7RDi+PmEYDZPXKMC7LMqmT3ZC4S52NM5ZAHhnCv2WzhtokpCE8x78 szkarEu5T1KbejDcXXSlW3a1WrSIkru3oNSREFDJTjyUb3v4oZ++wZdXuxPIl1zrRT/lDQ ahJsyL96QKGX7zZC3Koiq8WLSAiZusgOUSxgCE3EfA/EK+UTvPeYlDZBIQ/2dIUeuLhYln tQxRvkEXGIoF5t3nk+dnCfccJJ2tcsjB0GERPNiOHvNs1pmJku8BZORaVxPYHfiZxvzHOx /pvVJTO/ZsGCr8LJGGdBVtyl6lF8IrFHMzlwTq0pmcPU/OsHWmtBbswX9SYLA80dSCKeFg NvpKBZwffPMVTknny6VW3oEv+4Hr9LiDBdU0enW+QABuBw60PSgZQcSllXk8WdV2hlkeCB DL4/X36WIj/8m14et0Bse7IbpzJAe+INqg0TE5gqXeTmvJVXKsI0GUYWclx+mAfmgMxS+p rS3FaN5Abwc07lFcNhEvtzFuhQrHS4u7lME7SrxcH6plLeRPb7AAB6gnBRCTUmCzQCSc30 4QSHYEX74KL1qabyzaKYlaD30ptc4MV++UoklGRWR9mzkCIGgqpF5EDW9yT+SWBAMqwAPi 7xWmA5UoS738alF/6AIJkAAAADAQABAAACAFVHD2TMC8P/oERWo+Obp6WK3m9oqUufbfl2 PlXiZS57xvzlH6tmxLGT6PG/+jdpJqBNMRdxZsmiN559CzCjqIvhaJBC58q+hgBehmVdQJ eKE37VsHPYqc5K0rlFUEDAI6KxbzIOmVE1Q03wOf4bbQZJEHb1nFF/66gVCSpYbLZcv94n rqXNaZOy1P8PmX6RB9xv5Ga6PVo1FtqGTqE1Sti6U/HBKHn210DnNusoNs1dDYRlhhsuWS MYi5RW2+AIGbr02NyLEPS3q0xZiyJFpyvTlk88Vmh8zRcswhIhX0FcqHPBZ0B6WVnUIKYI klMNdRmrEggWDcum6qI7BoILvOCybZsPTgWvjIBiDvTVSt1uJeKV1AFQkcuJ/A8nt/MMJ1 cAgqKhZvHNBIioIPQGFcekoHgxD0qrSj+8vWbcGznIpOZMtuT2RqHLVmpnwcgeH+2N16wu dqstWb3DQMjh/8a6hGapEvjrfiRnZSy94n5+XKmtFSHCumegV4pYuv7qbx3Ssssowx8Y5b JnRU0I/MEs1Tfgl9YOvgfqpk/lrrXmmU+2kNsinT4SDW0ns2838aAhPd9JkcLgOqT880Zq GlZ3z5R4Oac/uEqn7vJ/3dn/JkvwuZBktfRvjBWQodlsqUUvB9KD5o1V/c7t6B9Z3TAeBF 37t9Gg7bpkCTRdSJOBAAABAHC6XMSDHOZNHhNR5ZiauxytY44rK76baiMDJYlRUIAxzDBL SYLo6ewp61pqehYBAj2JZNWtx2JbGkbYlXftAX6TxfQYQKy6IT0xvTm4eiP2rI9WcOuV8M upDX+Gus2a5oZZIiqrSTI/SXN38HQY+EqaQLlcwbPywhiuycp0K9LI64cqnBxwXCWMhG9E ShN72BLLSB+frkuhf2f8xpGLjeg7UrSAmJAfFCyhB+k+xyOBHQ2+dTQCJiJPHFhvdvosIV G4rQ8AKYbsV4NO0CG8DTUG+AzcZSqllERA90S5xaFJcVlvnSpMXoXHatxCddzal5e5S5gx cLTGqsBrsKmjwC4AAAEBAO5AGmTHJNRT9cCR6EsLETb3A9VPe17i9q4sGnTvhZv1Si1iaL xHJqCQkeByvAOZPw4iJtwlKP0xejCU2VzvTA5AS28SX5C+rHGAJtSxm9kSYgimDjvcQ0C1 bklO0XVcyNawi8V5dRq2O1cgPYHpNuZvgwtsfiIpDNhCC/lMam4QN48vkD6sPNoUrXcgAr W2prAFSzZykMSp+gyVH+TozKqDqQj/z75+g/Oqp0MDcFL05qTUTGNbLiGa2xzdX2OKyUXz SPj5NpE8FkiteNZYtrUPBGDJ8pAEwyX8RhbDyT4I69SBFOW9jSPM2V6OKe9+gCxImBqvPu IIFHotPW4Ds5cAAAEBANhzVkaNNtyBV2c3pieEh0aRIOP4+1wXjU60tg8OR7rL0aqJLvi2 OOC1Sej2I9UbB19aDsG3GBbtca5HCO+ScnGmARukNtsaEqrK0tOTmGxookgCnZqStSev4X aLbN+GNL19CJpPy/E8vpKEHyeEP5onJSr7uyEhUxxxzkHQmqGH/T5klCyrsDUJE+Ipx8rJ gKXBCiC3rKwePKrhsHlibdPiMdUBIYi49CsgudqkYOuFYu3B03yY2RE+7p8m1FQ1kmdSl5 eMi/LgQPIKwgGvs2a+jVf1riliBXStOeStP4XGNXd1EpHJ075b6UFC488kDJjDXsO21bIP 9j6OqOYkk08AAAAQamdhbmFwaW5AZHhjLmNvbQECAw== -----END OPENSSH PRIVATE KEY-----'
    sshKeySecureFile: 'id_rsa'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'javademo'
    publishLocation: 'Container'
    FileCopyOptions: 

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh_conn'
    sourceFolder: '/'
    contents: '**'
    targetFolder: '/home/jganapin/build'
    readyTimeout: '20000'